// SPDX-License-Identifier: Apache-2.0

namespace flatflow;

/// This table defines the operator set to identify operations in the
/// computational graph of a given PyTorch program. It is based on ATen operator
/// set so that each entry corresponds to the basic building block in the
/// computational graph while ensuring compatibility with PyTorch.
///
/// The latest version of ATen operator set can be found at
/// https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/native_functions.yaml
/// or by running `python3 -c "import torch; print(dir(torch.ops.aten))"`.
///
/// Note that this operator set is under development and more operators will be
/// added in the future.
enum Operator: ushort {
  _softmax,            // _softmax
  _to_copy,            // _to_copy
  _unsafe_view,        // _unsafe_view
  add_tensor,          // add.Tensor
  addmm,               // addmm
  alias,               // alias
  all_dim,             // all.dim
  arange,              // arange
  arange_start,        // arange.start
  bitwise_not,         // bitwise_not
  bmm,                 // bmm
  cat,                 // cat
  clone,               // clone
  copy,                // copy
  cumsum,              // cumsum
  embedding,           // embedding
  eq_scalar,           // eq.Scalar
  expand,              // expand
  full,                // full
  gelu,                // gelu
  gt_tensor,           // gt.Tensor
  lt_tensor,           // lt.Tensor
  masked_fill_scalar,  // masked_fill.Scalar
  mean_dim,            // mean.dim
  mm,                  // mm
  mul_scalar,          // mul.Scalar
  mul_tensor,          // mul.Tensor
  native_layer_norm,   // native_layer_norm
  neg,                 // neg
  ones,                // ones
  ones_like,           // ones_like
  permute,             // permute
  pow_tensor_scalar,   // pow.Tensor_Scalar
  relu,                // relu
  rsqrt,               // rsqrt
  rsub_scalar,         // rsub.Scalar
  scalar_tensor,       // scalar_tensor
  silu,                // silu
  slice_tensor,        // slice.Tensor
  slice_scatter,       // slice_scatter
  split_tensor,        // split.Tensor
  sub_tensor,          // sub.Tensor
  t,                   // t
  tanh,                // tanh
  transpose_int,       // transpose.int
  tril,                // tril
  triu,                // triu
  unsqueeze,           // unsqueeze
  view,                // view
  where_self,          // where.self
}
