// SPDX-License-Identifier: Apache-2.0

include "operator.fbs";
include "scalar_type.fbs";

/// `SymInt` records a value within the symbolic shape of a tensor.
struct SymInt {
  data: [long:2];
}

/// `TensorMetadata` is a structure containing pertinent information
/// about a tensor within a PyTorch program.
table TensorMetadata {
  dtype: ScalarType;
  shape: [SymInt] (required);
}

/// `Node` is a data structure that represents individual operations in the
/// computational graph. Each node contains an opcode identifying operators
/// and the input/output shapes of the operator. Unlike `torch.fx.Node`,
/// this excludes operations other than callsites to ATen operators;
/// i.e., operations whose `op` property are not `call_function`.
table Node {
  target: Operator;
  args:   [TensorMetadata] (required);
  meta:   TensorMetadata (required);
}

/// `Graph` is the main data structure for tracing a given PyTorch program at
/// the intermediate representation level. It consists of a series of `Node`s,
/// each representing callsites such as opcode and the input/output shapes of
/// the corresponding operator.
table Graph {
  nodes: [Node] (required);
}

root_type Graph;
