// SPDX-License-Identifier: Apache-2.0

/// This table defines data types to identify the precision of each tensor
/// operation in the computational graph of a given PyTorch program. It is based
/// on C10 scalar types, while types that are planned to be deprecated including
/// qint8 and bits2x4, or types that remain for historical reasons such as
/// complex64 are omitted.
///
/// The latest version of C10 scalar types can be found at
/// <https://github.com/pytorch/pytorch/blob/main/torch/headeronly/core/ScalarType.h>
/// or at <https://docs.pytorch.org/docs/stable/tensor_attributes.html#torch.dtype>.
///
/// Note that these data types are incomplete and more data types will be added
/// in the future.
enum ScalarType: ubyte {
  FLOAT32,          // float32
  FLOAT64,          // float64
  FLOAT16,          // float16
  BFLOAT16,         // bfloat16
  BOOL,             // bool
  INT8,             // int8
  INT16,            // int16
  INT32,            // int32
  INT64,            // int64
  UINT8,            // uint8
  UINT16,           // uint16
  UINT32,           // uint32
  UINT64,           // uint64
  FLOAT8_E4M3FN,    // float8_e4m3fn
  FLOAT8_E4M3FNUZ,  // float8_e4m3fnuz
  FLOAT8_E5M2,      // float8_e5m2
  FLOAT8_E5M2FNUZ,  // float8_e5m2fnuz
}
