// Copyright 2024 The FlatFlow Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef FLATFLOW_SCHEDULER_INTERNAL_PARTITION_H_
#define FLATFLOW_SCHEDULER_INTERNAL_PARTITION_H_

#include <algorithm>
#include <execution>
#include <iterator>
#include <queue>
#include <span>
#include <type_traits>
#include <utility>
#include <vector>

#include "absl/log/check.h"

#include "flatflow/data/internal/types.h"

namespace flatflow {
namespace internal {

// Subset<>
//
// Represents a partition generated by the balanced largest differencing method.
template <typename T, typename R>
  requires Numerical<R>
class Subset {
 public:
  using container_type = std::vector<T>;
  using value_type = typename container_type::value_type;
  using result_type = R;

  Subset(result_type result, const value_type &value) {
    sum_ = result;
    data_ = {value};
  }

  Subset(result_type result, value_type &&value) {
    sum_ = result;
    data_ = {std::move(value)};
  }

  Subset(result_type result, const container_type &data) : data_(data) {
    sum_ = result;
  }

  Subset(result_type result, container_type &&data) : data_(std::move(data)) {
    sum_ = result;
  }

  Subset() = delete;

  Subset(const Subset &other) = default;

  Subset &operator=(const Subset &other) = default;

  Subset(Subset &&other) = default;

  Subset &operator=(Subset &&other) = default;

  result_type &sum() { return sum_; }

  result_type sum() const { return sum_; }

  container_type &data() { return data_; }

  const container_type &data() const { return data_; }

  bool operator<(const Subset &other) const noexcept {
    return sum_ < other.sum();
  }

  // Subset::Join()
  //
  // Merges the two given partitions.
  void Join(const Subset &other) {
    sum_ += other.sum();
    data_.reserve(data_.size() + other.data().size());
    data_.insert(data_.cend(), std::make_move_iterator(other.data().begin()),
                 std::make_move_iterator(other.data().end()));
  }

 protected:
  result_type sum_;
  container_type data_;
};

// Solution<>
//
// Represents a partial solution used in the balanced largest differencing
// method.
template <typename T, typename R>
  requires Numerical<R>
class Solution {
 public:
  using container_type = std::vector<Subset<T, R>>;
  using value_type = typename container_type::value_type::value_type;
  using result_type = typename container_type::value_type::result_type;

  template <typename SizeType, typename UnaryFunc>
    requires(Unsigned<SizeType> &&
             Numerical<std::invoke_result_t<UnaryFunc, SizeType>>)
  Solution(std::span<const std::pair<const SizeType, value_type>> items,
           UnaryFunc func) {
    subsets_.reserve(items.size());
    std::for_each(std::execution::seq, items.begin(), items.end(),
                  [&](const auto &item) {
                    subsets_.emplace_back(func(item.first), item.second);
                  });
    difference_ = subsets_.back().sum() - subsets_.front().sum();
  }

  Solution() = delete;

  Solution(const Solution &other) = default;

  Solution &operator=(const Solution &other) = default;

  Solution(Solution &&other) = default;

  Solution &operator=(Solution &&other) = default;

  result_type &difference() { return difference_; }

  result_type difference() const { return difference_; }

  container_type &subsets() { return subsets_; }

  const container_type &subsets() const { return subsets_; }

  bool operator<(const Solution &other) const noexcept {
    return difference_ < other.difference();
  }

  // Solution::Combine()
  //
  // Differences the given two solutions by joining the subset with the smallest
  // sum in one with the subset with the largest sum in the other, the subset
  // with the second smallest sum in one with the subset with the second largest
  // sum in the other, and so on.
  void Combine(const Solution &other) {
    // clang-format off
    #pragma omp parallel for
    for (std::size_t index = 0; index < subsets_.size(); ++index) {
      subsets_[index].Join(other.subsets()[subsets_.size() - index - 1]);
    }
    // clang-format on

    std::sort(std::execution::par, subsets_.begin(), subsets_.end());
    difference_ = subsets_.back().sum() - subsets_.front().sum();
  }

 protected:
  result_type difference_;
  container_type subsets_;
};

// BLDM()
//
// Partitions the given items using the balanced largest differencing method
// (BLDM) of Michiels, Aarts, Korst, van Leeuwen and Spieksma from the paper
// `Computer-assisted proof of performance ratios for the Differencing Method`,
// a variant of LDM for balanced number partitioning with larger cardinalities.
// See https://doi.org/10.1016/j.disopt.2011.10.001 for the details.
template <typename IndexType, typename SizeType, typename UnaryFunc>
  requires(Unsigned<IndexType> && Unsigned<SizeType> &&
           Numerical<std::invoke_result_t<UnaryFunc, SizeType>>)
std::vector<Subset<IndexType, std::invoke_result_t<UnaryFunc, SizeType>>> BLDM(
    const std::vector<std::pair<const SizeType, IndexType>> &items,
    IndexType num_subsets, UnaryFunc func) {
  using value_type = IndexType;
  using result_type = std::invoke_result_t<UnaryFunc, SizeType>;

  if (items.empty()) {
    return std::vector<Subset<value_type, result_type>>();
  }

  const auto stride = static_cast<std::size_t>(num_subsets);
  CHECK_EQ(items.size() % stride, static_cast<std::size_t>(0));

  // Initially, BLDM starts with a sequence of `k` partial solutions, where each
  // partial solution is obtained from the `m` smallest remaining items.
  auto solutions = std::priority_queue<Solution<value_type, result_type>>();

  for (std::size_t offset = 0; offset < items.size(); offset += stride) {
    solutions.emplace(std::span(items).subspan(offset, stride), func);
  }

  // Next, the algorithm selects two partial solutions from the sequence, for
  // which the difference between the maximum and minimum subset sum is largest.
  // These two solutions are combined into a new partial solution by joining the
  // subset with the smallest sum in one solution with the subset with the
  // largest sum in another solution, the subset with the second smallest sum in
  // one solution with the subset with the second largest sum in another
  // solution, and so on. This process is called differencing the solutions.
  // The combined solution replaces the two solutions in the sequence, and we
  // iterate this differencing operation until only one solution in the sequence
  // remains, which is the balanced solution obtained by BLDM.
  while (1 < solutions.size()) {
    auto solution = solutions.top();
    solutions.pop();

    solution.Combine(solutions.top());
    solutions.pop();

    solutions.emplace(solution);
  }

  return solutions.top().subsets();
}

}  // namespace internal
}  // namespace flatflow

#endif  // FLATFLOW_SCHEDULER_INTERNAL_PARTITION_H_
