// SPDX-License-Identifier: Apache-2.0

//! Symbolic transformation and associated operator registry for its management and dynamic
//! dispatch.
//!
//! If you have need to register a new operator, please refer to [`OperatorRegistry`].

use core::ops::{self, Add, Mul};
use std::collections::HashMap;
use std::sync::{OnceLock, RwLock};
use std::time::Instant;

use log::info;
use rayon::iter::{IntoParallelRefIterator, ParallelIterator};

use crate::polynomial;

mod gcd;
pub mod graph;
pub use graph::Graph;
pub use graph::GraphIter;
pub use graph::Node;
pub use graph::SymInt;
pub use graph::TensorMetadata;
pub mod polynomial;
pub use polynomial::Polynomial;
pub mod scalar_type;
pub use scalar_type::promote_types;

// Automatically generated by the Flatbuffers compiler. Do not modify.
// @generated
#[allow(dead_code, unused_imports)]
mod graph_generated;
pub use graph_generated::root_as_graph;
#[allow(dead_code, unused_imports)]
mod operator_generated;
pub use operator_generated::Operator;
#[allow(dead_code, unused_imports)]
mod scalar_type_generated;
pub use scalar_type_generated::ScalarType;

/// `OperatorRegistry` holds the key information to identify operators and generate optimized
/// computation plans. It has an operator table where each value contains a mapping from a pair of
/// the corresponding operator and symbolic shapes to a symbolic expression for absolute number of
/// floating point operations (FLOPs), which we call symbolic transformation. These expressions are
/// created by measuring the absolute number of FLOPs or multiply-accumulates (MACs) for FMA
/// instructions required for each pair of operator and symbolic shapes, for a given size such as
/// sequence length.
///
/// Note: To register a new operator, please follow the instructions below:
///
/// * First, declare a new operator as an enumerator value of `Operator` in the FlatBuffers schema,
///   i.e., `flatflow/ops/operator.fbs`. The enumerator values are recommended to be sorted in order
///   of their original operator names (not the enumerator values themselves) for searching
///   convenience.
/// * Second, generate codes from the updated schema by running `make generate` in the root
///   directory of this source tree. This will create `src/ops/operator_generated.rs`, etc.
/// * Third, add a specialized implementation of `Fn` for the new operator; please refer to the
///   implementations below for supported operators. This step is checked at compile time.
/// * Finally, register the new operator to the operator table by calling
///   `OperatorRegistry::register` in the constructor below.
///   For the Python frontend, add the ATen counterpart and enumerator value as key and value
///   respectively to the operator table in `flatflow/ops/ops.py`.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct OperatorRegistry {
    vtable: HashMap<Operator, fn(Vec<TensorMetadata>, TensorMetadata) -> Polynomial>,
}

impl OperatorRegistry {
    /// Constructs a new operator table and registers symbolic transformations for all supported
    /// operators to it.
    ///
    /// Note that we provide only a handful of ATen operator set for now. The operator set is under
    /// development and more operators will be added in the future. For expanding the operator set,
    /// please refer to the note above.
    #[inline]
    pub fn new() -> Self {
        let mut registry = Self { vtable: HashMap::new() };
        registry.vtable.reserve(Operator::ENUM_VALUES.len());

        registry.register(Operator::_SOFTMAX, transform_impl::<{ Operator::_SOFTMAX.0 }>);
        registry.register(Operator::_TO_COPY, transform_impl::<{ Operator::_TO_COPY.0 }>);
        registry.register(Operator::_UNSAFE_VIEW, transform_impl::<{ Operator::_UNSAFE_VIEW.0 }>);
        registry.register(Operator::ADD_TENSOR, transform_impl::<{ Operator::ADD_TENSOR.0 }>);
        registry.register(Operator::ADDMM, transform_impl::<{ Operator::ADDMM.0 }>);
        registry.register(Operator::ALIAS, transform_impl::<{ Operator::ALIAS.0 }>);
        registry.register(Operator::ALL_DIM, transform_impl::<{ Operator::ALL_DIM.0 }>);
        registry.register(Operator::ARANGE, transform_impl::<{ Operator::ARANGE.0 }>);
        registry.register(Operator::ARANGE_START, transform_impl::<{ Operator::ARANGE_START.0 }>);
        registry.register(Operator::BITWISE_NOT, transform_impl::<{ Operator::BITWISE_NOT.0 }>);
        registry.register(Operator::BMM, transform_impl::<{ Operator::BMM.0 }>);
        registry.register(Operator::CAT, transform_impl::<{ Operator::CAT.0 }>);
        registry.register(Operator::CLONE, transform_impl::<{ Operator::CLONE.0 }>);
        registry.register(Operator::COPY, transform_impl::<{ Operator::COPY.0 }>);
        registry.register(Operator::CUMSUM, transform_impl::<{ Operator::CUMSUM.0 }>);
        registry.register(Operator::EMBEDDING, transform_impl::<{ Operator::EMBEDDING.0 }>);
        registry.register(Operator::EQ_SCALAR, transform_impl::<{ Operator::EQ_SCALAR.0 }>);
        registry.register(Operator::EXPAND, transform_impl::<{ Operator::EXPAND.0 }>);
        registry.register(Operator::FULL, transform_impl::<{ Operator::FULL.0 }>);
        registry.register(Operator::GELU, transform_impl::<{ Operator::GELU.0 }>);
        registry.register(Operator::GT_TENSOR, transform_impl::<{ Operator::GT_TENSOR.0 }>);
        registry.register(Operator::LT_TENSOR, transform_impl::<{ Operator::LT_TENSOR.0 }>);
        registry.register(
            Operator::MASKED_FILL_SCALAR,
            transform_impl::<{ Operator::MASKED_FILL_SCALAR.0 }>,
        );
        registry.register(Operator::MEAN_DIM, transform_impl::<{ Operator::MEAN_DIM.0 }>);
        registry.register(Operator::MM, transform_impl::<{ Operator::MM.0 }>);
        registry.register(Operator::MUL_SCALAR, transform_impl::<{ Operator::MUL_SCALAR.0 }>);
        registry.register(Operator::MUL_TENSOR, transform_impl::<{ Operator::MUL_TENSOR.0 }>);
        registry.register(
            Operator::NATIVE_LAYER_NORM,
            transform_impl::<{ Operator::NATIVE_LAYER_NORM.0 }>,
        );
        registry.register(Operator::NEG, transform_impl::<{ Operator::NEG.0 }>);
        registry.register(Operator::ONES, transform_impl::<{ Operator::ONES.0 }>);
        registry.register(Operator::ONES_LIKE, transform_impl::<{ Operator::ONES_LIKE.0 }>);
        registry.register(Operator::PERMUTE, transform_impl::<{ Operator::PERMUTE.0 }>);
        registry.register(
            Operator::POW_TENSOR_SCALAR,
            transform_impl::<{ Operator::POW_TENSOR_SCALAR.0 }>,
        );
        registry.register(Operator::RELU, transform_impl::<{ Operator::RELU.0 }>);
        registry.register(Operator::RSQRT, transform_impl::<{ Operator::RSQRT.0 }>);
        registry.register(Operator::RSUB_SCALAR, transform_impl::<{ Operator::RSUB_SCALAR.0 }>);
        registry.register(Operator::SCALAR_TENSOR, transform_impl::<{ Operator::SCALAR_TENSOR.0 }>);
        registry.register(Operator::SILU, transform_impl::<{ Operator::SILU.0 }>);
        registry.register(Operator::SLICE_TENSOR, transform_impl::<{ Operator::SLICE_TENSOR.0 }>);
        registry.register(Operator::SLICE_SCATTER, transform_impl::<{ Operator::SLICE_SCATTER.0 }>);
        registry.register(Operator::SPLIT_TENSOR, transform_impl::<{ Operator::SPLIT_TENSOR.0 }>);
        registry.register(Operator::SUB_TENSOR, transform_impl::<{ Operator::SUB_TENSOR.0 }>);
        registry.register(Operator::T, transform_impl::<{ Operator::T.0 }>);
        registry.register(Operator::TANH, transform_impl::<{ Operator::TANH.0 }>);
        registry.register(Operator::TRANSPOSE_INT, transform_impl::<{ Operator::TRANSPOSE_INT.0 }>);
        registry.register(Operator::TRIL, transform_impl::<{ Operator::TRIL.0 }>);
        registry.register(Operator::TRIU, transform_impl::<{ Operator::TRIU.0 }>);
        registry.register(Operator::UNSQUEEZE, transform_impl::<{ Operator::UNSQUEEZE.0 }>);
        registry.register(Operator::VIEW, transform_impl::<{ Operator::VIEW.0 }>);
        registry.register(Operator::WHERE_SELF, transform_impl::<{ Operator::WHERE_SELF.0 }>);

        registry
    }

    /// Returns the global operator registry.
    ///
    /// This is useful when you want to register a new operator from your extern crate. For example,
    /// to register a new operator named `NOP`, one might write:
    ///
    /// ```rust
    /// use flatflow::ops::{Operator, OperatorRegistry, Polynomial, TensorMetadata};
    /// use flatflow::polynomial;
    ///
    /// const NOP: Operator = Operator(u16::MAX);
    ///
    /// #[allow(unused_variables)]
    /// #[inline]
    /// fn transform_impl_nop(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
    ///     polynomial!()
    /// }
    ///
    /// let mut registry = OperatorRegistry::global().write().unwrap();
    /// registry.register(NOP, transform_impl_nop);
    /// ```
    #[inline]
    pub fn global() -> &'static RwLock<Self> {
        static REGISTRY: OnceLock<RwLock<OperatorRegistry>> = OnceLock::new();
        REGISTRY.get_or_init(|| RwLock::new(Self::new()))
    }

    /// Registers `op` to the operator table.
    ///
    /// If `op` was not registered in the operator table, `None` is returned. Otherwise the symbolic
    /// transformation for `op` is replaced with the given `func`, and a function pointer to the old
    /// one is returned.
    #[inline]
    pub fn register(
        &mut self,
        op: Operator,
        func: fn(Vec<TensorMetadata>, TensorMetadata) -> Polynomial,
    ) -> Option<fn(Vec<TensorMetadata>, TensorMetadata) -> Polynomial> {
        self.vtable.insert(op, func)
    }

    /// Removes `op` from the operator table.
    ///
    /// If `op` was not registered in the operator table, `None` is returned. Otherwise a function
    /// pointer to the symbolic transformation for `op` is returned.
    #[inline]
    pub fn deregister(
        &mut self,
        op: Operator,
    ) -> Option<fn(Vec<TensorMetadata>, TensorMetadata) -> Polynomial> {
        self.vtable.remove(&op)
    }

    /// Executes the symbolic transformation corresponding to the given operator.
    ///
    /// # Panics
    ///
    /// Panics if `op` was not registered in the operator table.
    #[inline]
    pub fn dispatch(
        &self,
        op: Operator,
        args: Vec<TensorMetadata>,
        meta: TensorMetadata,
    ) -> Polynomial {
        self.vtable.get(&op).unwrap_or_else(|| {
            panic!(
                "Could not find symbolic transformation for {} (opcode: {})",
                op.variant_name().unwrap_or("UNDEFINED"),
                op.0
            )
        })(args, meta)
    }
}

impl Default for OperatorRegistry {
    #[inline]
    fn default() -> Self {
        Self::new()
    }
}

/// Trait for implementing symbolic transformations.
///
/// `OPCODE` indicates the opcode of the operator to be implemented. `args` and `meta` contain
/// tensor metadata such as data type and symbolic shapes of each tensor. These arguments are
/// automatically obtained via symbolic tracing of PyTorch FX.
trait Fn<const OPCODE: u16> {
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial;
}

impl Fn<{ Operator::_SOFTMAX.0 }> for () {
    /// func: _softmax(Tensor self, int dim, bool half_to_float) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // _softmax applies the softmax function to `self`.
        //
        // Note: _softmax requires five FLOPs for each element.
        // Approximate FLOPs breakdown can be found at:
        // https://github.com/tensorflow/tensorflow/blob/v2.18.0/tensorflow/python/profiler/internal/flops_registry.py
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!(5 * scale), Mul::mul)
    }
}

impl Fn<{ Operator::_TO_COPY.0 }> for () {
    /// func: _to_copy(Tensor self, *, ScalarType? dtype=None, Layout? layout=None,
    ///                Device? device=None, bool? pin_memory=None, bool non_blocking=False,
    ///                MemoryFormat? memory_format=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // _to_copy copies a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::_UNSAFE_VIEW.0 }> for () {
    /// func: _unsafe_view(Tensor self, SymInt[] size) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // _unsafe_view is a tensor view operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::ADD_TENSOR.0 }> for () {
    /// func: add.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // add.Tensor adds `other`, scaled by `alpha`, to `self`.
        //
        // Note: As in the case of mul.Tensor, we have found that add.Scalar is replaced by
        // add.Tensor with a single argument due to constant folding. That is, if two arguments are
        // given, one addition and one multiplication are required for each element; but if there is
        // only one argument, just one addition occurs for each element. add.Tensor also supports
        // broadcasting to a common shape, necessitating the use of output shape.
        let len = args.len() as i64;
        assert!(len.is_positive());

        let mut dtype = args.get(0).unwrap().dtype;
        if 1 < len {
            dtype = promote_types(dtype, args.get(1).unwrap().dtype);
        }

        let scale: i64 = dtype.into();
        meta.shape.iter().map(Polynomial::from).fold(polynomial!(len * scale), Mul::mul)
    }
}

impl Fn<{ Operator::ADDMM.0 }> for () {
    /// func: addmm(Tensor self, Tensor mat1, Tensor mat2, *, Scalar beta=1,
    ///             Scalar alpha=1) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        assert_eq!(args.len(), 3);
        assert_eq!(args.get(1).unwrap().shape.len(), 2);
        assert_eq!(args.get(2).unwrap().shape.len(), 2);

        // addmm performs a matrix multiplication of the matrices `mat1` and `mat2`. The matrix
        // `self` is added to the final result. `alpha` and `beta` are scaling factors on
        // matrix-vector product between `mat1` and `mat2` and the added matrix `self` respectively.
        // If `mat1` is a (n x m) tensor and `mat2` is a (m x p) tensor, then it produces a (n x p)
        // tensor with n x m x p MACs. For scaling and addition, it requires additional 3 x n x p
        // FLOPs.
        let n = args.get(1).unwrap().shape.get(0).unwrap();
        let m = args.get(1).unwrap().shape.get(1).unwrap();
        assert_eq!(m, args.get(2).unwrap().shape.get(0).unwrap());

        let p = args.get(2).unwrap().shape.get(1).unwrap();

        let dtype = promote_types(args.get(1).unwrap().dtype, args.get(2).unwrap().dtype);
        let mm_scale: i64 = dtype.into();

        let dtype = promote_types(dtype, args.get(0).unwrap().dtype);
        let add_scale: i64 = dtype.into();

        let n: Polynomial = n.into();
        let m: Polynomial = m.into();
        let p: Polynomial = p.into();

        n * p * (m * mm_scale + 3 * add_scale)
    }
}

impl Fn<{ Operator::ALIAS.0 }> for () {
    /// func: alias(Tensor(a) self) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // alias is a tensor view operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::ALL_DIM.0 }> for () {
    /// func: all.dim(Tensor self, int dim, bool keepdim=False) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // all.dim tests if all elements in the row evaluate to true, so technically it has zero
        // FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::ARANGE.0 }> for () {
    /// func: arange(Scalar end, *, ScalarType? dtype=None, Layout? layout=None,
    ///              Device? device=None, bool? pin_memory=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // arange returns a tensor, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::ARANGE_START.0 }> for () {
    /// func: arange.start(Scalar start, Scalar end, *, ScalarType? dtype=None, Layout? layout=None,
    ///                    Device? device=None, bool? pin_memory=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // arange.start returns a tensor, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::BITWISE_NOT.0 }> for () {
    /// func: bitwise_not(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // bitwise_not computes the bitwise NOT of the given input tensor, so technically it has
        // zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::BMM.0 }> for () {
    /// func: bmm(Tensor self, Tensor mat2) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        assert_eq!(args.len(), 2);
        assert_eq!(args.get(0).unwrap().shape.len(), 3);
        assert_eq!(args.get(1).unwrap().shape.len(), 3);

        // bmm performs a batch matrix-matrix product of matrices `self` and `mat2`. `self` and
        // `mat2` must be 3-D tensors each containing the same number of matrices. If `self` is a
        // (b x n x m) tensor and `mat2` is a (b x m x p) tensor, then it produces a (b x n x p)
        // tensor with b x n x m x p MACs.
        let b = args.get(0).unwrap().shape.get(0).unwrap();

        // The first dimension of `self` and `mat2` must be symbolically identical.
        assert_eq!(b, args.get(1).unwrap().shape.get(0).unwrap());

        let n = args.get(0).unwrap().shape.get(1).unwrap();
        let m = args.get(0).unwrap().shape.get(2).unwrap();

        // The last dimension of `self` and the middle dimension of `mat2` must be symbolically
        // identical.
        assert_eq!(m, args.get(1).unwrap().shape.get(1).unwrap());

        let p = args.get(1).unwrap().shape.get(2).unwrap();

        let scale: i64 =
            promote_types(args.get(0).unwrap().dtype, args.get(1).unwrap().dtype).into();

        let b: Polynomial = b.into();
        let n: Polynomial = n.into();
        let m: Polynomial = m.into();
        let p: Polynomial = p.into();

        b * n * m * p * scale
    }
}

impl Fn<{ Operator::CAT.0 }> for () {
    /// func: cat(Tensor[] tensors, int dim=0) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // cat concatenates tensors in the given dimension, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::CLONE.0 }> for () {
    /// func: clone(Tensor self, *, MemoryFormat? memory_format=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // clone copies a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::COPY.0 }> for () {
    /// func: copy(Tensor self, Tensor src, bool non_blocking=False) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // copy copies a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::CUMSUM.0 }> for () {
    /// func: cumsum(Tensor self, int dim, *, ScalarType? dtype=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // cumsum returns the cumulative sum of elements of `self` in the dimension `dim`.
        //
        // Note: Its absolute number of FLOPs depends on the value of `dim`, which cannot be deduced
        // from the tensor metadata since cumsum always returns a tensor with the same shape as
        // `self`; the exact number of FLOPs is obtained by subtracting one from the corresponding
        // dimension and then multiplying the size of the remaining dimensions, but here we ignore
        // that subtraction.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::EMBEDDING.0 }> for () {
    /// func: embedding(Tensor weight, Tensor indices, SymInt padding_idx=-1,
    ///                 bool scale_grad_by_freq=False, bool sparse=False) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // embedding is a dictionary lookup, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::EQ_SCALAR.0 }> for () {
    /// func: eq.Scalar(Tensor self, Scalar other) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // eq.Scalar computes element-wise equality, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::EXPAND.0 }> for () {
    /// func: expand(Tensor(a) self, SymInt[] size, *, bool implicit=False) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // expand is a tensor view operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::FULL.0 }> for () {
    /// func: full(SymInt[] size, Scalar fill_value, *, ScalarType? dtype=None, Layout? layout=None,
    ///            Device? device=None, bool? pin_memory=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // full creates a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::GELU.0 }> for () {
    /// func: gelu(Tensor self, *, str approximate='none') -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // gelu applies the gaussian error linear unit (GELU) function to `self` in element-wise.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!(14 * scale), Mul::mul)
    }
}

impl Fn<{ Operator::GT_TENSOR.0 }> for () {
    /// func: gt.Tensor(Tensor self, Tensor other) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // gt.Tensor computes element-wise logical connectives, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::LT_TENSOR.0 }> for () {
    /// func: lt.Tensor(Tensor self, Tensor other) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // lt.Tensor computes element-wise logical connectives, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::MASKED_FILL_SCALAR.0 }> for () {
    /// func: masked_fill.Scalar(Tensor self, Tensor mask, Scalar value) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // masked_fill.Scalar is an out-of-place version of masked_fill_.Scalar, so it has zero
        // FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::MEAN_DIM.0 }> for () {
    /// func: mean.dim(Tensor self, int[1]? dim, bool keepdim=False, *,
    ///                ScalarType? dtype=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // mean.dim returns the mean value of each row of `self` in the given dimension `dim`.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::MM.0 }> for () {
    /// func: mm(Tensor self, Tensor mat2) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        assert_eq!(args.len(), 2);
        assert_eq!(args.get(0).unwrap().shape.len(), 2);
        assert_eq!(args.get(1).unwrap().shape.len(), 2);

        // mm performs a matrix multiplication of the matrices `self` and `mat2`. If `self` is a
        // (n x m) tensor and `mat2` is a (m x p) tensor, then it produces a (n x p) tensor with
        // n x m x p MACs.
        let n = args.get(0).unwrap().shape.get(0).unwrap();
        let m = args.get(0).unwrap().shape.get(1).unwrap();

        // The last dimension of `self` and the first dimension of `mat2` must be symbolically
        // identical.
        assert_eq!(m, args.get(1).unwrap().shape.get(0).unwrap());

        let p = args.get(1).unwrap().shape.get(1).unwrap();

        let scale: i64 =
            promote_types(args.get(0).unwrap().dtype, args.get(1).unwrap().dtype).into();

        let n: Polynomial = n.into();
        let m: Polynomial = m.into();
        let p: Polynomial = p.into();

        n * m * p * scale
    }
}

impl Fn<{ Operator::MUL_SCALAR.0 }> for () {
    /// func: mul.Scalar(Tensor self, Scalar other) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // mul.Scalar multiplies `self` by `other` in element-wise.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::MUL_TENSOR.0 }> for () {
    /// func: mul.Tensor(Tensor self, Tensor other) -> Tensor
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // mul.Tensor multiplies `self` by `other` in element-wise.
        //
        // Note: As shown above, mul.Tensor gets two tensor arguments but we have found that there
        // is a bug during symbolic tracing where mul.Scalar is replaced by mul.Tensor with a single
        // argument due to constant folding. Moreover, mul.Tensor supports broadcasting to a common
        // shape, making it difficult to trace FLOPs with input shapes alone; mul.Tensor has the
        // same FLOPs as mul.Scalar, and we leverage the output shape that reflects the
        // broadcasting.
        assert!(!args.is_empty());

        let mut dtype = args.get(0).unwrap().dtype;
        if 1 < args.len() {
            dtype = promote_types(dtype, args.get(1).unwrap().dtype);
        }

        let scale: i64 = dtype.into();
        meta.shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::NATIVE_LAYER_NORM.0 }> for () {
    /// func: native_layer_norm(Tensor input, SymInt[] normalized_shape, Tensor? weight,
    ///                         Tensor? bias, float eps) -> (Tensor, Tensor, Tensor)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        assert_eq!(args.len(), 3);

        // native_layer_norm applies layer normalization over a mini-batch of inputs
        // `input`. The mean and standard deviation are calculated over the last `d`
        // dimensions, where `d` is the dimension of `normalized_shape`. `weight` and
        // `bias` are learnable affine transform parameters of `normalized_shape`.
        let d = args.get(1).unwrap().shape.len();
        assert_eq!(d, args.get(2).unwrap().shape.len());

        let dtype = args.get(0).unwrap().dtype;
        let scale: i64 = dtype.into();
        let last_d = args
            .get(0)
            .unwrap()
            .shape
            .iter()
            .rev()
            .take(d)
            .map(Polynomial::from)
            .fold(polynomial!(3 * scale), Mul::mul);

        let dtype = promote_types(dtype, args.get(1).unwrap().dtype);
        let weight_scale: i64 = dtype.into();

        let dtype = promote_types(dtype, args.get(2).unwrap().dtype);
        let bias_scale: i64 = dtype.into();

        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!((scale << 1) + weight_scale + bias_scale), Mul::mul)
            + last_d
    }
}

impl Fn<{ Operator::NEG.0 }> for () {
    /// func: neg(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // neg returns a new tensor with the negative of the elements of `self`.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::ONES.0 }> for () {
    /// func: ones(SymInt[] size, *, ScalarType? dtype=None, Layout? layout=None,
    ///            Device? device=None, bool? pin_memory=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // ones creates a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::ONES_LIKE.0 }> for () {
    /// func: ones_like(Tensor self, *, ScalarType? dtype=None, Layout? layout=None,
    ///                 Device? device=None, bool? pin_memory=None,
    ///                 MemoryFormat? memory_format=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // ones_like creates a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::PERMUTE.0 }> for () {
    /// func: permute(Tensor(a) self, int[] dims) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // permute is a tensor view operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::POW_TENSOR_SCALAR.0 }> for () {
    /// func: pow.Tensor_Scalar(Tensor self, Scalar exponent) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // pow.Tensor_Scalar takes the power of each element in `self` with `exponent`.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::RELU.0 }> for () {
    /// func: relu(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // relu applies the rectified linear unit (ReLU) function to `self` in element-wise.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::RSQRT.0 }> for () {
    /// func: rsqrt(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // rsqrt computes the element-wise reciprocal square root of `self`.
        //
        // Note: rsqrt requires two FLOPs for each element.
        // Approximate FLOPs breakdown can be found at:
        // https://github.com/tensorflow/tensorflow/blob/v2.18.0/tensorflow/python/profiler/internal/flops_registry.py
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0).unwrap().shape.iter().map(Polynomial::from).fold(polynomial!(scale), Mul::mul)
    }
}

impl Fn<{ Operator::RSUB_SCALAR.0 }> for () {
    /// func: rsub.Scalar(Tensor self, Scalar other, Scalar alpha=1) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // rsub.Scalar subtracts `self`, scaled by `alpha`, from `other`.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!(scale << 1), Mul::mul)
    }
}

impl Fn<{ Operator::SCALAR_TENSOR.0 }> for () {
    /// func: scalar_tensor(Scalar s, *, ScalarType? dtype=None, Layout? layout=None,
    ///                     Device? device=None, bool? pin_memory=None) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // scalar_tensor creates a tensor, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::SILU.0 }> for () {
    /// func: silu(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // silu applies the sigmoid linear unit (SiLU) function to `self`
        // in element-wise.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!(scale << 2), Mul::mul)
    }
}

impl Fn<{ Operator::SLICE_TENSOR.0 }> for () {
    /// func: slice.Tensor(Tensor(a) self, int dim=0, SymInt? start=None, SymInt? end=None,
    ///                    SymInt step=1) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // slice.Tensor is a tensor view operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::SLICE_SCATTER.0 }> for () {
    /// func: slice_scatter(Tensor self, Tensor src, int dim=0, SymInt? start=None,
    ///                     SymInt? end=None, SymInt step=1) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // slice_scatter embeds the values of `src` into `self` at the given dimension, so
        // technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::SPLIT_TENSOR.0 }> for () {
    /// func: split.Tensor(Tensor(a -> *) self, SymInt split_size, int dim=0) -> Tensor(a)[]
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // split.Tensor splits a tensor into chunks, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::SUB_TENSOR.0 }> for () {
    /// func: sub.Tensor(Tensor self, Tensor other, *, Scalar alpha=1) -> Tensor
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // sub.Tensor subtracts `other`, scaled by `alpha`, from `self`.
        //
        // Note: As in the case of mul.Tensor, we have found that sub.Scalar is replaced by
        // sub.Tensor with a single argument due to constant folding. That is, if two arguments are
        // given, one subtraction and one multiplication are required for each element; but if there
        // is only one argument, just one subtraction occurs for each element. sub.Tensor also
        // supports broadcasting to a common shape, necessitating the use of output shape.
        let len = args.len() as i64;
        assert!(len.is_positive());

        let mut dtype = args.get(0).unwrap().dtype;
        if 1 < len {
            dtype = promote_types(dtype, args.get(1).unwrap().dtype);
        }

        let scale: i64 = dtype.into();
        meta.shape.iter().map(Polynomial::from).fold(polynomial!(len * scale), Mul::mul)
    }
}

impl Fn<{ Operator::T.0 }> for () {
    /// func: t(Tensor(a) self) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // t is a dimension swap, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::TANH.0 }> for () {
    /// func: tanh(Tensor self) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // tanh applies the hyperbolic tangent (tanh) function to `self` in element-wise.
        assert_eq!(args.len(), 1);

        let scale: i64 = args.get(0).unwrap().dtype.into();
        args.get(0)
            .unwrap()
            .shape
            .iter()
            .map(Polynomial::from)
            .fold(polynomial!(6 * scale), Mul::mul)
    }
}

impl Fn<{ Operator::TRANSPOSE_INT.0 }> for () {
    /// func: transpose.int(Tensor(a) self, int dim0, int dim1) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // transpose.int is a dimension swap, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::TRIL.0 }> for () {
    /// func: tril(Tensor self, int diagonal=0) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // tril is a masking operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::TRIU.0 }> for () {
    /// func: triu(Tensor self, int diagonal=0) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // triu is a masking operation, so technically it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::UNSQUEEZE.0 }> for () {
    /// func: unsqueeze(Tensor(a) self, int dim) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // unsqueeze inserts a singleton dimension at the specified position, so it has zero FLOPs.
        polynomial!()
    }
}

impl Fn<{ Operator::VIEW.0 }> for () {
    /// func: view(Tensor(a) self, SymInt[] size) -> Tensor(a)
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // view is a tensor view operation, so technically it has zero FLOPs.
        //
        // See https://pytorch.org/docs/stable/tensor_view.html.
        polynomial!()
    }
}

impl Fn<{ Operator::WHERE_SELF.0 }> for () {
    /// func: where.self(Tensor condition, Tensor self, Tensor other) -> Tensor
    #[allow(unused_variables)]
    #[inline]
    fn call(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial {
        // where.self is an element-wise branching operation, so it has zero FLOPs.
        polynomial!()
    }
}

/// This is a blanket implementation for dynamic dispatch of symbolic transformations on each node
/// in a computational graph.
#[inline]
fn transform_impl<const OPCODE: u16>(args: Vec<TensorMetadata>, meta: TensorMetadata) -> Polynomial
where
    (): Fn<OPCODE>,
{
    <() as Fn<OPCODE>>::call(args, meta)
}

/// Transforms the given computational `graph` into a curried function via symbolic transformation.
///
/// Note that operator resolutions are delegated to the global operator registry so that any
/// user-defined symbolic transformations that have been registered globally are also taken into
/// account.
///
/// # Panics
///
/// The registry is read under a shared lock. If a writer panics while holding the underlying lock,
/// the lock becomes poisoned; in such case this function also panics when attempting to acquire the
/// registry read lock.
pub fn transform<T>(graph: graph_generated::Graph<'_>) -> impl ops::Fn(T) -> Result<i64, T::Error>
where
    T: TryInto<i64>,
{
    let now = Instant::now();

    let registry = OperatorRegistry::global().read().unwrap_or_else(|err| {
        panic!("Maybe a writer panics while holding the underlying lock: {}", err)
    });

    let mut expr = graph
        .par_iter()
        .map(Node::from)
        .map(|node| registry.dispatch(node.target, node.args, node.meta))
        .reduce(Default::default, Add::add);
    expr.normalize();

    info!("Traversing a graph with {} nodes took {:?}", graph.nodes().len(), now.elapsed());

    move |value| expr.eval(value)
}
